version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: greencodes_test
        container_name: greencodes_test_app_container
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
        environment:
            - APACHE_DOCUMENT_ROOT=/var/www/html/public
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: greencodes_test_mysql_container
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: greencodes_technical_test_db
            MYSQL_USER: greencodes_technical_test_user
            MYSQL_PASSWORD: password
        volumes:
            - dbdata:/var/lib/mysql

volumes:
    dbdata:
